spring:
  application:
    name: blog-core-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    port: 6379
    password:
    host: 192.168.31.180
  datasource:
    name: myblogDatabase
    url: jdbc:mysql://192.168.31.180:3308/myblog
    username: root
    password: 890890
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      server-addr: 192.168.31.180:8848
#      discovery:
#        cluster-name: NJ # 集群名称
#        namespace: 6187f42f-0662-4811-abd3-112ac0e56918
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则,调用其他微服务时候，优先调用同集群下的实例

feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数

#blog:
#  mail:
#    sendMail: false

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
#  instance:
#    prefer-ip-address: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

#blog:
#  mail:
#    sendMail: false