spring:
  application:
    name: blogCoreService
  datasource:
    name: myblogDatabase
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: 890890iop
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml