spring:
  application:
    name: blog-mail-service
  cloud:
    nacos:
      server-addr: localhost:80
      discovery:
        cluster-name: NJ # 集群名称
        namespace: 6187f42f-0662-4811-abd3-112ac0e56918
  mail:
    username: njj1108@outlook.com
    password: 890890iopP
    host: smtp.office365.com
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl:
            socketFactory:
              class: com.sun.mail.util.MailSSLSocketFactory
              fallback: false
blog:
  mail:
    newBlogMailTemplate: NewBlogNotification