server:
  port: 10010 # 网关端口
spring:
#  main:
#    web-application-type: reactive
  application:
    name: gateway-server # 服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:80 # Nacos地址
      discovery:
        namespace: 6187f42f-0662-4811-abd3-112ac0e56918
    gateway:
      routes: # 网关路由配置
        - id: blog-core-service # 路由id，自定义，只要唯一即可
          filters:
            - StripPrefix=1
#          uri: http://127.0.0.1:8080 # 路由的目标地址 http就是固定地址
          uri: lb://blog-core-service # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/core/** # 这个是按照路径匹配，只要以/core/开头就符合要求